#!/bin/bash
#==============================================================================
#
#          FILE:  failed-login-alert
#
#         USAGE: 
#
#   DESCRIPTION: This script is used to send failed login alert to admin
#
#        AUTHOR:  Team LocalHost
#       VERSION:  1.0
#       CREATED:  23/03/2019 14:38:58 AM IST
#===============================================================================


PATH=/bin:/usr/bin

username=$(grep "failure" /var/log/auth.log | tail -1 | cut -d '=' -f 8)
hostname=$(hostname)
timestamp=$(date)
admin_email=
heroku_url=

# cURL request to append data in GraphQl Hasura
/usr/bin/curl "$heroku_url" \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'content-type: application/json' \
-H 'Accept: */*' \
-H 'Connection: keep-alive' \
--data-binary '{"query":"mutation {\n  insert_login_failed(objects: {hostname: \"'"$hostname"'\", timestamp: \"'"$timestamp"'\", username: \"'"$username"'\"}) {\n    affected_rows\n  }\n}\n","variables":null}' --compressed &$

# Mailing the Admin
echo "username: $username try to login in hostname: $hostname at timestamp: $timestamp" | mail -s "$username Failed Login" $admin_email

exit 0