#!/bin/bash
#==============================================================================
#
#          FILE:  login-alert
#
#         USAGE: 
#
#   DESCRIPTION: This script is used to send login alert to admin
#
#        AUTHOR:  Team LocalHost
#       VERSION:  1.0
#       CREATED:  23/03/2019 10:12:08 AM IST
#===============================================================================

PATH=/bin:/usr/bin

username=$(whoami)
hostname=$(hostname)
timestamp=$(date)
admin_email=
heroku_url=


# cURL request to append data in GraphQl Hasura
/usr/bin/curl $heroku_url \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'content-type: application/json' \
-H 'Accept: */*' \
-H 'Connection: keep-alive' \
--data-binary '{"query":"mutation {\n  insert_login_details(objects: {hostname: \"'"$hostname"'\", timestamp: \"'"$timestamp"'\", username: \"'"$username"'\"}) {\n    affected_rows\n  }\n}\n","variables":null}' --compressed &> /dev/null

# Mailing the Admin
echo "username: $username login in hostname: $hostname at timestamp: $timestamp" | mail -s "$username Logged in" $admin_email

exit 0